services:
  backend:
    build: ./backend
    ports:
      - "9000:4000"
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend