services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "4000"
    environment:
      - MONGODB_URI=mongodb+srv://elkiwebdesign:0mrazzWaXrloYGdZ@cluster0.g0enka0.mongodb.net/realestate?retryWrites=true&w=majority
      - JWT_SECRET=your-secret-key-here

  frontend:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - backend