version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:80"   # HTTP: host 8080 -> container 80
      - "8443:443"  # HTTPS: host 8443 -> container 443
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Uncomment if you want to use .env file
    # env_file:
    #   - .env

  # Optional: Uncomment if you need a database
  # db:
  #   image: postgres:15-alpine
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: realestate
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   db_data: 