services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=realestate

  backend:
    build: ./backend
    ports:
      - "9000:4000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb+srv://elkiwebdesign:0mrazzWaXrloYGdZ@cluster0.g0enka0.mongodb.net/

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend