version: '3.8'
services:
  frontend:
    build: .
    container_name: realestate-frontend
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
  backend:
    build: ./backend
    container_name: realestate-backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    expose:
      - "4000"
  nginx:
    image: nginx:alpine
    container_name: realestate-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend

# volumes:
#   db_data: 