version: '3.8'

networks:
  dev:

services:
  frontend:
    build: ./frontend
    container_name: realestate-frontend
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - dev
  backend:
    build: ./backend
    container_name: realestate-backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    expose:
      - "4000"
    networks:
      - dev
  nginx:
    image: nginx:stable-alpine
    container_name: realestate-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    networks:
      - dev

# volumes:
#   db_data: 