version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:80"   # HTTP: host 8080 -> container 80
      - "8443:443"  # HTTPS: host 8443 -> container 443
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://backend:4000/api
    restart: unless-stopped
    depends_on:
      - backend
    # Uncomment if you want to use .env file
    # env_file:
    #   - .env

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://db:27017/realestate
      - PORT=4000
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"

# volumes:
#   db_data: 